

#ifndef TABLEID_H
#define TABLEID_H

namespace tabledef
{
	enum
	{
		TABLE_ACCOUNTGOLD,
		TABLE_ACCOUNTIDENTITY,
		TABLE_BLACK_LISTS,
		TABLE_CAMP,
		TABLE_CHALLENGERUSER,
		TABLE_COMMAND,
		TABLE_CROSS_PERSONRANK,
		TABLE_CROSSRECORD,
		TABLE_CROSSSTATUS,
		TABLE_DAILYFIND,
		TABLE_ENEMY,
		TABLE_FISHPOOL,
		TABLE_FRIENDS,
		TABLE_GLOBALROLE,
		TABLE_GUILD,
		TABLE_GUILDAPPLYFOR,
		TABLE_GUILDEVENT,
		TABLE_GUILDMEMBER,
		TABLE_HOTKEY,
		TABLE_ITEMLIST,
		TABLE_LOGIN,
		TABLE_MAIL,
		TABLE_OFFLINEREGISTER,
		TABLE_PERSONRANK,
		TABLE_PUBLICNOTICE,
		TABLE_PUBLICSALE,
		TABLE_ROLE,
		TABLE_ROLE_ATTR_DETAIL,
		TABLE_ROLE_ATTR_DETAIL10,
		TABLE_ROLE_ATTR_DETAIL2,
		TABLE_ROLE_ATTR_DETAIL3,
		TABLE_ROLE_ATTR_DETAIL4,
		TABLE_ROLE_ATTR_DETAIL5,
		TABLE_ROLE_ATTR_DETAIL6,
		TABLE_ROLE_ATTR_DETAIL7,
		TABLE_ROLE_ATTR_DETAIL8,
		TABLE_ROLE_ATTR_DETAIL9,
		TABLE_ROLE_ID_MAP,
		TABLE_ROLE_NAME_MAP,
		TABLE_ROLESKILL,
		TABLE_SPACERECORD,
		TABLE_SYSTEMMAIL,
		TABLE_TEAMRANK,
		TABLE_TUODAN,
		TABLE_WORLDSTATUS,
		TABLE_WORLDSTATUS2,
		TABLE_WORLDSTATUS3,
		TABLE_COUNT,
	};
}

#include "tablefieldid.h"

#endif

