

#ifndef TABLEFIELDID_H
#define TABLEFIELDID_H

namespace tabledef
{
	enum TABLE_ACCOUNTGOLD_FIELDS
	{
		ACCOUNTGOLD_ACCOUNTGOLD_ID,
		ACCOUNTGOLD_PLAT_USER_NAME,
		ACCOUNTGOLD_ROLE_ID,
		ACCOUNTGOLD_GOLD,
		ACCOUNTGOLD_GOLD_HISTORY,
		ACCOUNTGOLD_LAST_GET_GOLD_TIME,
		ACCOUNTGOLD_AUTHORITY_TYPE,
		TABLE_ACCOUNTGOLD_MAXINDEX
	};

	enum TABLE_ACCOUNTIDENTITY_FIELDS
	{
		ACCOUNTIDENTITY_IDACCOUNTIDENTITY,
		ACCOUNTIDENTITY_PLAT_USER_NAME,
		ACCOUNTIDENTITY_NAME,
		ACCOUNTIDENTITY_IDENTITY_NUM,
		TABLE_ACCOUNTIDENTITY_MAXINDEX
	};

	enum TABLE_BLACK_LISTS_FIELDS
	{
		BLACK_LISTS_IDBLACK,
		BLACK_LISTS_ROLE_ID,
		BLACK_LISTS_BLACK_INDEX,
		BLACK_LISTS_FOR_INDEX,
		BLACK_LISTS_BLACK_UID,
		BLACK_LISTS_BLACK_NAME,
		BLACK_LISTS_SEX,
		BLACK_LISTS_PROF,
		TABLE_BLACK_LISTS_MAXINDEX
	};

	enum TABLE_CAMP_FIELDS
	{
		CAMP_IDCAMP,
		CAMP_CAMP_TYPE,
		CAMP_ROLE_COUNT,
		CAMP_GUILD_COUNT,
		CAMP_RICH_LEVEL,
		CAMP_EARNINGS_END_TIME1,
		CAMP_EARNINGS1,
		CAMP_EARNINGS_END_TIME2,
		CAMP_EARNINGS2,
		CAMP_TOTAL_CAPABILITY,
		TABLE_CAMP_MAXINDEX
	};

	enum TABLE_CHALLENGERUSER_FIELDS
	{
		CHALLENGERUSER_CHALLENGER_USER_ID,
		CHALLENGERUSER_ROLE_ID,
		CHALLENGERUSER_RANKPOS,
		CHALLENGERUSER_CHALLENGE_USER_DATA,
		CHALLENGERUSER_COMMON_DATA,
		CHALLENGERUSER_REPORT_INFO_DATA,
		CHALLENGERUSER_ROLE_APPEARANCE_DATA,
		TABLE_CHALLENGERUSER_MAXINDEX
	};

	enum TABLE_COMMAND_FIELDS
	{
		COMMAND_IDCOMMAND,
		COMMAND_CREATOR,
		COMMAND_CREATETIME,
		COMMAND_TYPE,
		COMMAND_CMD,
		COMMAND_CONFIRMTIME,
		TABLE_COMMAND_MAXINDEX
	};

	enum TABLE_CROSS_PERSONRANK_FIELDS
	{
		CROSS_PERSONRANK_IDCROSSPERSONRANK,
		CROSS_PERSONRANK_RANK_INDEX,
		CROSS_PERSONRANK_UUID,
		CROSS_PERSONRANK_USER_NAME,
		CROSS_PERSONRANK_ROLE_SEX,
		CROSS_PERSONRANK_ROLE_PROF,
		CROSS_PERSONRANK_ROLE_CAMP,
		CROSS_PERSONRANK_ROLE_EXP,
		CROSS_PERSONRANK_ROLE_LEVEL,
		CROSS_PERSONRANK_RANK_TYPE,
		CROSS_PERSONRANK_RANK_VALUE,
		CROSS_PERSONRANK_RECORD_INDEX,
		CROSS_PERSONRANK_FLEXIBLE_LL,
		CROSS_PERSONRANK_FLEXIBLE_NAME,
		CROSS_PERSONRANK_FLEXIBLE_INT,
		CROSS_PERSONRANK_VIP_LEVEL,
		TABLE_CROSS_PERSONRANK_MAXINDEX
	};

	enum TABLE_CROSSRECORD_FIELDS
	{
		CROSSRECORD_IDCROSSRECORD,
		CROSSRECORD_ROLE_ID,
		CROSSRECORD_ROLE_NAME,
		CROSSRECORD_LEVEL,
		CROSSRECORD_SEX,
		CROSSRECORD_PROF,
		CROSSRECORD_CAMP,
		CROSSRECORD_RECORD_DATA,
		CROSSRECORD_APPEARANCE_DATA,
		TABLE_CROSSRECORD_MAXINDEX
	};

	enum TABLE_CROSSSTATUS_FIELDS
	{
		CROSSSTATUS_IDCROSSSTATUS,
		CROSSSTATUS_FOR_INDEX,
		CROSSSTATUS_LAST_UPDATE_DAYID,
		CROSSSTATUS_CROSS_PERSON_RANK_TITLE_DATA,
		CROSSSTATUS_CROSS_ACTIVITY_DATA,
		TABLE_CROSSSTATUS_MAXINDEX
	};

	enum TABLE_DAILYFIND_FIELDS
	{
		DAILYFIND_IDDAILYFIND,
		DAILYFIND_ROLE_ID,
		DAILYFIND_FOR_INDEX,
		DAILYFIND_FIND_TIME,
		DAILYFIND_ROLE_LEVEL,
		DAILYFIND_FIND_INDEX,
		DAILYFIND_PARAM,
		DAILYFIND_PARAM1,
		DAILYFIND_FIND_COUNT,
		TABLE_DAILYFIND_MAXINDEX
	};

	enum TABLE_ENEMY_FIELDS
	{
		ENEMY_IDENEMY,
		ENEMY_ROLE_ID,
		ENEMY_FOR_INDEX,
		ENEMY_ENEMY_UID,
		ENEMY_ENEMY_PLAT_TYPE,
		ENEMY_KILL_COUNT,
		ENEMY_LAST_KILL_TIME,
		ENEMY_ENEMY_INDEX,
		ENEMY_BE_KILL_COUNT,
		TABLE_ENEMY_MAXINDEX
	};

	enum TABLE_FISHPOOL_FIELDS
	{
		FISHPOOL_IDFISHPOOL,
		FISHPOOL_FISH_ROLE_ID,
		FISHPOOL_COMMON_DATA,
		FISHPOOL_RAISE_FISH_DATA,
		FISHPOOL_TODAY_RAISE_RECORD,
		TABLE_FISHPOOL_MAXINDEX
	};

	enum TABLE_FRIENDS_FIELDS
	{
		FRIENDS_IDFRIEND,
		FRIENDS_ROLE_ID,
		FRIENDS_FOR_INDEX,
		FRIENDS_FRIEND_UID,
		FRIENDS_INTIMACY,
		FRIENDS_TEAM_TODAY_INTIMACY,
		FRIENDS_FRIEND_INDEX,
		FRIENDS_GIFT_COUNT,
		FRIENDS_FAVORABLE_IMPRESSION,
		FRIENDS_DAY_CHAT_COUNT,
		FRIENDS_ADD_TIMESTAMP,
		TABLE_FRIENDS_MAXINDEX
	};

	enum TABLE_GLOBALROLE_FIELDS
	{
		GLOBALROLE_ID_GLOBALROLE,
		GLOBALROLE_ROLE_ID,
		GLOBALROLE_LITTLE_PET_DATA,
		GLOBALROLE_LOVE_TREE_DATA,
		GLOBALROLE_LOVE_CONTRACT_DATA,
		GLOBALROLE_JING_LING_HOME_DATA,
		GLOBALROLE_ROLE_FIGHTING_DATA,
		GLOBALROLE_QINGYUAN_GLOBAL_DATA,
		GLOBALROLE_ROLE_APPEARANCE_DATA,
		GLOBALROLE_COMMON_DATA_GLOBAL_DATA,
		GLOBALROLE_SPOUSEHOME_DATA,
		TABLE_GLOBALROLE_MAXINDEX
	};

	enum TABLE_GUILD_FIELDS
	{
		GUILD_GUILD_ID_INC,
		GUILD_GUILD_ID,
		GUILD_GUILD_NAME,
		GUILD_CREATE_TIME,
		GUILD_GUILD_LEVEL,
		GUILD_GUILD_EXP,
		GUILD_CAMP,
		GUILD_NOTICE,
		GUILD_LAST_UPDATE_DAYID,
		GUILD_WARNING_DISMISS_DAYS,
		GUILD_APPLYFOR_SETUP,
		GUILD_LAST_ACTIVE_TIME,
		GUILD_AUTO_KICKOUT_SETUP,
		GUILD_GUILD_MAX_CAPABILITY,
		GUILD_APPLYFOR_NEED_CAPABILITY,
		GUILD_APPLYFOR_NEED_LEVEL,
		GUILD_LAST_UPLEVEL_TIMESTAMP,
		GUILD_CALLIN_TIMES,
		GUILD_TODAY_MONSTER_FINISH_SEQ,
		GUILD_TODAY_MONSTER_FINISH_USERNAME,
		GUILD_COMMON_DATA,
		GUILD_ACTIVE_DEGREE,
		GUILD_BOSS_LIST,
		GUILD_STORGE,
		GUILD_ENEMY_LIST,
		TABLE_GUILD_MAXINDEX
	};

	enum TABLE_GUILDAPPLYFOR_FIELDS
	{
		GUILDAPPLYFOR_IDGUILDAPPLYFOR,
		GUILDAPPLYFOR_GUILD_ID,
		GUILDAPPLYFOR_APPLY_FOR_INDEX,
		GUILDAPPLYFOR_FOR_INDEX,
		GUILDAPPLYFOR_UID,
		GUILDAPPLYFOR_APPLYFOR_TIME,
		TABLE_GUILDAPPLYFOR_MAXINDEX
	};

	enum TABLE_GUILDEVENT_FIELDS
	{
		GUILDEVENT_IDGUILDEVENT,
		GUILDEVENT_GUILD_ID,
		GUILDEVENT_EVENT_INDEX,
		GUILDEVENT_FOR_INDEX,
		GUILDEVENT_EVENT_TYPE,
		GUILDEVENT_EVENT_OWNER,
		GUILDEVENT_EVENT_OWNER_POST,
		GUILDEVENT_EVENT_TIME,
		GUILDEVENT_BIG_EVENT,
		GUILDEVENT_CANNOT_REMOVE,
		GUILDEVENT_PARAM0,
		GUILDEVENT_PARAM1,
		GUILDEVENT_PARAM2,
		GUILDEVENT_PARAM3,
		GUILDEVENT_SPARAM0,
		TABLE_GUILDEVENT_MAXINDEX
	};

	enum TABLE_GUILDMEMBER_FIELDS
	{
		GUILDMEMBER_IDGUILDMEMBER,
		GUILDMEMBER_GUILD_ID,
		GUILDMEMBER_MEMBER_INDEX,
		GUILDMEMBER_FOR_INDEX,
		GUILDMEMBER_UID,
		GUILDMEMBER_POST,
		GUILDMEMBER_GONGXIAN,
		GUILDMEMBER_TOTAL_GONGXIAN,
		GUILDMEMBER_JOIN_TIME,
		GUILDMEMBER_LAST_LOGIN_TIME,
		GUILDMEMBER_LUCKY_COLOR,
		GUILDMEMBER_TODAY_GUILD_PAO_SAIZI_TIMES,
		GUILDMEMBER_TODAY_LAST_GUILD_PAO_SAIZI_TIME,
		GUILDMEMBER_TODAY_GUILD_SAIZI_SCORE,
		GUILDMEMBER_MAZE_LAYER,
		GUILDMEMBER_MAZE_COMPLETE_TIME,
		GUILDMEMBER_COMMON_DATA,
		TABLE_GUILDMEMBER_MAXINDEX
	};

	enum TABLE_HOTKEY_FIELDS
	{
		HOTKEY_HOTKEY_ID,
		HOTKEY_ROLE_ID,
		HOTKEY_HOTKEY_INDEX,
		HOTKEY_FOR_INDEX,
		HOTKEY_HOTKEY_ITEM_TYPE,
		HOTKEY_HOTKEY_ITEM_ID,
		TABLE_HOTKEY_MAXINDEX
	};

	enum TABLE_ITEMLIST_FIELDS
	{
		ITEMLIST_IDITEMLIST,
		ITEMLIST_ROLE_ID,
		ITEMLIST_ITEMLIST_INDEX,
		ITEMLIST_FOR_INDEX,
		ITEMLIST_ITEM_ID,
		ITEMLIST_IS_BIND,
		ITEMLIST_NUM,
		ITEMLIST_INVALID_TIME,
		ITEMLIST_GOLD_PRICE,
		ITEMLIST_PARAM,
		TABLE_ITEMLIST_MAXINDEX
	};

	enum TABLE_LOGIN_FIELDS
	{
		LOGIN_LOGIN_ID,
		LOGIN_PLAT_USER_NAME,
		LOGIN_DB_INDEX,
		LOGIN_ROLE_ID_1,
		LOGIN_ROLE_ID_2,
		LOGIN_ROLE_ID_3,
		LOGIN_LASTLOGINTIME,
		LOGIN_CREATETIME,
		LOGIN_FORBIDTIME,
		LOGIN_IS_ANTI_WALLOW,
		LOGIN_FORBID_TIME_1,
		LOGIN_FORBID_TIME_2,
		LOGIN_FORBID_TIME_3,
		TABLE_LOGIN_MAXINDEX
	};

	enum TABLE_MAIL_FIELDS
	{
		MAIL_IDMAIL,
		MAIL_UID,
		MAIL_MAIL_INDEX,
		MAIL_FOR_INDEX,
		MAIL_SENDER_UID,
		MAIL_SENDER_NAME,
		MAIL_RECV_TIME,
		MAIL_KIND,
		MAIL_IS_READ,
		MAIL_IS_LOCK,
		MAIL_COIN,
		MAIL_COIN_BIND,
		MAIL_GOLD,
		MAIL_GOLD_BIND,
		MAIL_SUBJECT,
		MAIL_CONTENT,
		MAIL_ITEM_ID1,
		MAIL_ITEM_IS_BIND1,
		MAIL_ITEM_NUM1,
		MAIL_ITEM_INVALID_TIME1,
		MAIL_ITEM_PARAM1,
		MAIL_ITEM_ID2,
		MAIL_ITEM_IS_BIND2,
		MAIL_ITEM_NUM2,
		MAIL_ITEM_INVALID_TIME2,
		MAIL_ITEM_PARAM2,
		MAIL_ITEM_ID3,
		MAIL_ITEM_IS_BIND3,
		MAIL_ITEM_NUM3,
		MAIL_ITEM_INVALID_TIME3,
		MAIL_ITEM_PARAM3,
		MAIL_VIRTUAL_ITEM_DATA,
		TABLE_MAIL_MAXINDEX
	};

	enum TABLE_OFFLINEREGISTER_FIELDS
	{
		OFFLINEREGISTER_IDOFFLINEREGISTER,
		OFFLINEREGISTER_ROLE_ID,
		OFFLINEREGISTER_LAST_DIVORCE_TIME,
		OFFLINEREGISTER_INCREASE_CHARM,
		OFFLINEREGISTER_CHONGZHI_CMD_FLAG,
		OFFLINEREGISTER_RED_PAPER_CONSUME_GOLD,
		OFFLINEREGISTER_RED_PAPER_LUCKY_VALUE,
		OFFLINEREGISTER_SPACE_CAI_CONUT,
		OFFLINEREGISTER_SPACE_GIFT_COUNT,
		OFFLINEREGISTER_QINGYUAN_BLESS_DAYS,
		OFFLINEREGISTER_GUILD_BOX_INFO,
		OFFLINEREGISTER_COMMON_DATA,
		TABLE_OFFLINEREGISTER_MAXINDEX
	};

	enum TABLE_PERSONRANK_FIELDS
	{
		PERSONRANK_IDPERSONRANK,
		PERSONRANK_RANK_INDEX,
		PERSONRANK_UID,
		PERSONRANK_USER_NAME,
		PERSONRANK_FLEXIBLE_NAME,
		PERSONRANK_ROLE_SEX,
		PERSONRANK_ROLE_PROF,
		PERSONRANK_ROLE_CAMP,
		PERSONRANK_ROLE_VIP_LEVEL,
		PERSONRANK_ROLE_EXP,
		PERSONRANK_ROLE_LEVEL,
		PERSONRANK_RANK_TYPE,
		PERSONRANK_RANK_VALUE,
		PERSONRANK_RECORD_INDEX,
		PERSONRANK_FLEXIBLE_INT,
		PERSONRANK_FLEXIBLE_LL,
		TABLE_PERSONRANK_MAXINDEX
	};

	enum TABLE_PUBLICNOTICE_FIELDS
	{
		PUBLICNOTICE_IDPUBLICNOTICE,
		PUBLICNOTICE_CREATOR,
		PUBLICNOTICE_CREATETIME,
		PUBLICNOTICE_BEGIN_SEND_TIME,
		PUBLICNOTICE_SEND_INTERVAL,
		PUBLICNOTICE_END_SEND_TIME,
		PUBLICNOTICE_NEXT_SEND_TIME,
		PUBLICNOTICE_CONTENT,
		PUBLICNOTICE_TYPE,
		PUBLICNOTICE_COLOR,
		PUBLICNOTICE_IS_FORBID,
		PUBLICNOTICE_IS_URGENT,
		TABLE_PUBLICNOTICE_MAXINDEX
	};

	enum TABLE_PUBLICSALE_FIELDS
	{
		PUBLICSALE_IDPUBLICSALE,
		PUBLICSALE_SELLER_UID,
		PUBLICSALE_SELLER_NAME,
		PUBLICSALE_SALE_INDEX,
		PUBLICSALE_FOR_INDEX,
		PUBLICSALE_ITEM_ID,
		PUBLICSALE_ITEM_IS_BIND,
		PUBLICSALE_ITEM_SALE_TYPE,
		PUBLICSALE_ITEM_NUM,
		PUBLICSALE_COLOR,
		PUBLICSALE_LEVEL,
		PUBLICSALE_PROF,
		PUBLICSALE_EQUIP_ORDER,
		PUBLICSALE_GOLD_PRICE,
		PUBLICSALE_SALE_VALUE,
		PUBLICSALE_PRICE_TYPE,
		PUBLICSALE_SALE_ITEM_TYPE,
		PUBLICSALE_SALE_TIME,
		PUBLICSALE_DUE_TIME,
		PUBLICSALE_ITEM_INVALID_TIME,
		PUBLICSALE_ITEM_PARAM,
		TABLE_PUBLICSALE_MAXINDEX
	};

	enum TABLE_ROLE_FIELDS
	{
		ROLE_ROLE_INC_ID,
		ROLE_ROLE_ID,
		ROLE_ROLE_NAME,
		ROLE_AVATAR,
		ROLE_SEX,
		ROLE_SCENE_ID,
		ROLE_LAST_SCENE_ID,
		ROLE_LEVEL,
		ROLE_PROFESSIONAL,
		ROLE_CREATE_TIME,
		ROLE_ONLINE_TIME,
		ROLE_IS_ONLINE,
		ROLE_LAST_SAVE_TIME,
		ROLE_COUNTRY,
		ROLE_IS_CHONGZHI,
		ROLE_IS_MICRO_PC,
		ROLE_PLAT_SPID,
		TABLE_ROLE_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL_FIELDS
	{
		ROLE_ATTR_DETAIL_ROLE_ATTR_DETAIL_ID,
		ROLE_ATTR_DETAIL_ROLE_ID,
		ROLE_ATTR_DETAIL_ATTR_DATA,
		ROLE_ATTR_DETAIL_ROLE_NAME,
		ROLE_ATTR_DETAIL_LEVEL,
		ROLE_ATTR_DETAIL_SEX,
		ROLE_ATTR_DETAIL_PROF,
		ROLE_ATTR_DETAIL_CAMP,
		ROLE_ATTR_DETAIL_GOLD,
		ROLE_ATTR_DETAIL_GOLD_BIND,
		ROLE_ATTR_DETAIL_COIN,
		ROLE_ATTR_DETAIL_COIN_BIND,
		ROLE_ATTR_DETAIL_GUILD_ID,
		ROLE_ATTR_DETAIL_AVATAR,
		ROLE_ATTR_DETAIL_AVATAR_TIMESTAMP,
		ROLE_ATTR_DETAIL_VIP_TYPE,
		ROLE_ATTR_DETAIL_EVIL,
		ROLE_ATTR_DETAIL_HP,
		ROLE_ATTR_DETAIL_MAX_HP,
		ROLE_ATTR_DETAIL_MP,
		ROLE_ATTR_DETAIL_MAX_MP,
		ROLE_ATTR_DETAIL_GONGJI,
		ROLE_ATTR_DETAIL_FANGYU,
		ROLE_ATTR_DETAIL_MINGZHONG,
		ROLE_ATTR_DETAIL_SHANBI,
		ROLE_ATTR_DETAIL_BAOJI,
		ROLE_ATTR_DETAIL_JIANREN,
		ROLE_ATTR_DETAIL_FUJIA_SHANGHAI,
		ROLE_ATTR_DETAIL_DIKANG_SHANGHAI,
		ROLE_ATTR_DETAIL_PER_JINGZHUN,
		ROLE_ATTR_DETAIL_PER_BAOJI,
		ROLE_ATTR_DETAIL_PER_KANGBAO,
		ROLE_ATTR_DETAIL_PER_POFANG,
		ROLE_ATTR_DETAIL_PER_MIANSHANG,
		ROLE_ATTR_DETAIL_CAPABILITY,
		ROLE_ATTR_DETAIL_MAX_CAPABILITY,
		ROLE_ATTR_DETAIL_LOVER_UID,
		ROLE_ATTR_DETAIL_LOVER_NAME,
		ROLE_ATTR_DETAIL_AUTHORITY_TYPE,
		ROLE_ATTR_DETAIL_FORBID_TALK_TIME,
		ROLE_ATTR_DETAIL_SUBLOCK_PW,
		ROLE_ATTR_DETAIL_ROLECHEST_DATA_LEN,
		ROLE_ATTR_DETAIL_MENTALITY_DATA,
		ROLE_ATTR_DETAIL_VIP_DATA,
		ROLE_ATTR_DETAIL_ACTIVE_DEGREE_DATA,
		ROLE_ATTR_DETAIL_ROLESHOP_DATA,
		ROLE_ATTR_DETAIL_WELFARE_DATA,
		ROLE_ATTR_DETAIL_ROLEHANGUP_DATA,
		ROLE_ATTR_DETAIL_ROLECUSTOM_DATA,
		ROLE_ATTR_DETAIL_ITEMCOLDDOWN_DATA,
		ROLE_ATTR_DETAIL_EVALUATE_DATA,
		ROLE_ATTR_DETAIL_MONITOR_DATA,
		ROLE_ATTR_DETAIL_TITLE_DATA,
		ROLE_ATTR_DETAIL_HUSONGTASK_DATA,
		ROLE_ATTR_DETAIL_ROLEACTIVITY_DATA,
		ROLE_ATTR_DETAIL_FBTOWERDEFEND_DATA,
		ROLE_ATTR_DETAIL_LAST_SINGLE_CHAT_MONITOR_TIME,
		ROLE_ATTR_DETAIL_LAST_SINGLE_CHAT_MONITOR_MSG,
		ROLE_ATTR_DETAIL_LAST_WORLD_CHAT_MONITOR_TIME,
		ROLE_ATTR_DETAIL_LAST_WORLD_CHAT_MONITOR_MSG,
		ROLE_ATTR_DETAIL_LAST_MAIL_MONITOR_TIME,
		ROLE_ATTR_DETAIL_LAST_MAIL_MONITOR_SUBJECT,
		ROLE_ATTR_DETAIL_TODAY_ONLINE_TIME,
		ROLE_ATTR_DETAIL_LASTDAY_ONLINE_TIME,
		ROLE_ATTR_DETAIL_COMMON_DATA,
		ROLE_ATTR_DETAIL_WING_DATA,
		TABLE_ROLE_ATTR_DETAIL_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL10_FIELDS
	{
		ROLE_ATTR_DETAIL10_ROLE_ATTR_DETAIL10_ID,
		ROLE_ATTR_DETAIL10_ROLE_ID,
		ROLE_ATTR_DETAIL10_ORANGE_EQUIP_COLLECT_DATA,
		ROLE_ATTR_DETAIL10_YAOSHI_DATA,
		ROLE_ATTR_DETAIL10_TOUSHI_DATA,
		ROLE_ATTR_DETAIL10_QILINBI_DATA,
		ROLE_ATTR_DETAIL10_MASK_DATA,
		ROLE_ATTR_DETAIL10_JINJIESYS_REWARD_DATA,
		ROLE_ATTR_DETAIL10_ROLE_BIG_SMALL_GOAL_DATA,
		ROLE_ATTR_DETAIL10_DATA_PAGE_LEN,
		ROLE_ATTR_DETAIL10_DATA_PAGE,
		TABLE_ROLE_ATTR_DETAIL10_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL2_FIELDS
	{
		ROLE_ATTR_DETAIL2_ROLE_ATTR_DETAIL2_ID,
		ROLE_ATTR_DETAIL2_ROLE_ID,
		ROLE_ATTR_DETAIL2_ROLECHEST_DATA,
		ROLE_ATTR_DETAIL2_EFFECT_DATA,
		ROLE_ATTR_DETAIL2_EQUIPFB_DATA,
		ROLE_ATTR_DETAIL2_GUILD_TASK_DATA,
		ROLE_ATTR_DETAIL2_NEWEQUIPFB_DATA,
		ROLE_ATTR_DETAIL2_STONE_DATA,
		ROLE_ATTR_DETAIL2_GUILD_XIANSHU_DATA,
		ROLE_ATTR_DETAIL2_TASKRECORD_DATA,
		ROLE_ATTR_DETAIL2_TASKINFO_DATA,
		ROLE_ATTR_DETAIL2_ROLE_SUPPLY_DATA,
		ROLE_ATTR_DETAIL2_MAZE_DATA,
		ROLE_ATTR_DETAIL2_XIANNV_DATA,
		ROLE_ATTR_DETAIL2_STORY_FB_DATA,
		ROLE_ATTR_DETAIL2_CONVERT_RECORD_DATA,
		TABLE_ROLE_ATTR_DETAIL2_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL3_FIELDS
	{
		ROLE_ATTR_DETAIL3_ROLE_ATTR_DETAIL3_ID,
		ROLE_ATTR_DETAIL3_ROLE_ID,
		ROLE_ATTR_DETAIL3_OTHER_MODULE_DATA,
		ROLE_ATTR_DETAIL3_QINGYUAN_DATA,
		ROLE_ATTR_DETAIL3_ROLE_GOAL_DATA,
		ROLE_ATTR_DETAIL3_HISTORY_CAP_DATA,
		ROLE_ATTR_DETAIL3_SKILL_OTHER_DATA,
		ROLE_ATTR_DETAIL3_ROLE_GUILD_DATA,
		ROLE_ATTR_DETAIL3_SHENGWANG_DATA,
		ROLE_ATTR_DETAIL3_CHENGJIU_DATA,
		ROLE_ATTR_DETAIL3_DAILYFB_DATA,
		ROLE_ATTR_DETAIL3_LIFESKILL_DATA,
		ROLE_ATTR_DETAIL3_BABY_DATA,
		ROLE_ATTR_DETAIL3_SHENGE_SYSTEM_DATA,
		ROLE_ATTR_DETAIL3_ZERO_GIFT_DATA,
		ROLE_ATTR_DETAIL3_MYSTERIOUS_SHOP_IN_MALL_DATA,
		ROLE_ATTR_DETAIL3_FRIEND_EXP_BOTTLE_DATA,
		ROLE_ATTR_DETAIL3_SHENSHOU,
		ROLE_ATTR_DETAIL3_IMG_FULING_DATA,
		TABLE_ROLE_ATTR_DETAIL3_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL4_FIELDS
	{
		ROLE_ATTR_DETAIL4_ROLE_ATTR_DETAIL4_ID,
		ROLE_ATTR_DETAIL4_ROLE_ID,
		ROLE_ATTR_DETAIL4_TUHAOJIN_DATA,
		ROLE_ATTR_DETAIL4_BIGCHATFACE_DATA,
		ROLE_ATTR_DETAIL4_PET_DATA,
		ROLE_ATTR_DETAIL4_PHASE_FB_DATA,
		ROLE_ATTR_DETAIL4_VIP_FB_DATA,
		ROLE_ATTR_DETAIL4_HUASHEN_DATA,
		ROLE_ATTR_DETAIL4_MAGIC_CARD_DATA,
		ROLE_ATTR_DETAIL4_MITAMA_DATA,
		ROLE_ATTR_DETAIL4_EQUIPMENT_DATA,
		ROLE_ATTR_DETAIL4_CHINESE_ZODIAC_DATA,
		ROLE_ATTR_DETAIL4_FRIEND_GIFT,
		ROLE_ATTR_DETAIL4_FOLLOW_BOSS,
		ROLE_ATTR_DETAIL4_GOLD_VIP,
		ROLE_ATTR_DETAIL4_RUNE_SYSTEM,
		ROLE_ATTR_DETAIL4_MAGICAL_PRECIOUS_DATA,
		TABLE_ROLE_ATTR_DETAIL4_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL5_FIELDS
	{
		ROLE_ATTR_DETAIL5_ROLE_ATTR_DETAIL5_ID,
		ROLE_ATTR_DETAIL5_ROLE_ID,
		ROLE_ATTR_DETAIL5_MULTI_MOUNT_DATA,
		ROLE_ATTR_DETAIL5_PERSONALIZE_WINDOW_DATA,
		ROLE_ATTR_DETAIL5_XUNZHANG,
		ROLE_ATTR_DETAIL5_ZHIBAO,
		ROLE_ATTR_DETAIL5_JINGLING,
		ROLE_ATTR_DETAIL5_XIANNV_SHOUHU,
		ROLE_ATTR_DETAIL5_JINGLING_FAZHEN,
		ROLE_ATTR_DETAIL5_JINGLING_GUANGHUAN,
		ROLE_ATTR_DETAIL5_SHENZHOU_WEAPON_DATA,
		ROLE_ATTR_DETAIL5_LIEMING,
		ROLE_ATTR_DETAIL5_LIEMING_BAG,
		ROLE_ATTR_DETAIL5_CARDZU,
		ROLE_ATTR_DETAIL5_ZHUANSHENG_EQUIP,
		ROLE_ATTR_DETAIL5_SHENBING,
		ROLE_ATTR_DETAIL5_TUITUFB_DATA,
		ROLE_ATTR_DETAIL5_CLOAK,
		ROLE_ATTR_DETAIL5_ROLE_PRECIOUS_BOSS,
		TABLE_ROLE_ATTR_DETAIL5_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL6_FIELDS
	{
		ROLE_ATTR_DETAIL6_ROLE_ATTR_DETAIL6_ID,
		ROLE_ATTR_DETAIL6_ROLE_ID,
		ROLE_ATTR_DETAIL6_COUPLE_MOUNT_DATA,
		ROLE_ATTR_DETAIL6_SHENYIN_DATA,
		ROLE_ATTR_DETAIL6_ELEMENT_HEART_DATA,
		ROLE_ATTR_DETAIL6_SHENGXINGZHULI,
		ROLE_ATTR_DETAIL6_SHIZHUANG_DATA,
		ROLE_ATTR_DETAIL6_FABAO_DATA,
		ROLE_ATTR_DETAIL6_FEIXIAN_DATA,
		ROLE_ATTR_DETAIL6_TALENT_DATA,
		ROLE_ATTR_DETAIL6_JINJIE_TALENT_DATA,
		ROLE_ATTR_DETAIL6_ARMOR_FB_DATA,
		ROLE_ATTR_DETAIL6_BOSSCARD_DATA,
		ROLE_ATTR_DETAIL6_TASK_ZHUANZHI_DATA,
		ROLE_ATTR_DETAIL6_DISCOUNT_BUY_DATA,
		TABLE_ROLE_ATTR_DETAIL6_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL7_FIELDS
	{
		ROLE_ATTR_DETAIL7_ROLE_ATTR_DETAIL7_ID,
		ROLE_ATTR_DETAIL7_ROLE_ID,
		ROLE_ATTR_DETAIL7_CROSS_GLOBAL_DATA,
		ROLE_ATTR_DETAIL7_ZHUANZHI_EQUIP_DATA,
		ROLE_ATTR_DETAIL7_ROLE_CROSS_DATA,
		ROLE_ATTR_DETAIL7_HESHENLUOSHU_DATA,
		ROLE_ATTR_DETAIL7_SHENGQI_DATA,
		ROLE_ATTR_DETAIL7_SEAL_DATA,
		ROLE_ATTR_DETAIL7_DRESSING_ROOM_DATA,
		ROLE_ATTR_DETAIL7_CHALLENGE_FB_DATA,
		ROLE_ATTR_DETAIL7_ROLE_CROSS_RAND_ACTIVITY_DATA,
		ROLE_ATTR_DETAIL7_CROSS_GOAL_DATA,
		TABLE_ROLE_ATTR_DETAIL7_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL8_FIELDS
	{
		ROLE_ATTR_DETAIL8_ROLE_ATTR_DETAIL8_ID,
		ROLE_ATTR_DETAIL8_ROLE_ID,
		ROLE_ATTR_DETAIL8_UPGRADE_MANAGER_DATA,
		ROLE_ATTR_DETAIL8_SHENQI_DATA,
		ROLE_ATTR_DETAIL8_MINGHUN2_DATA,
		ROLE_ATTR_DETAIL8_PERSON_PROFESS_DATA,
		ROLE_ATTR_DETAIL8_XIANZUNKA_DATA,
		ROLE_ATTR_DETAIL8_EQUIP_BAPTIZE_DATA,
		ROLE_ATTR_DETAIL8_MOJIE,
		ROLE_ATTR_DETAIL8_FB_PERSONBOSS_DATA,
		ROLE_ATTR_DETAIL8_GREATE_SOLDIER_DATA,
		ROLE_ATTR_DETAIL8_LOTTERY_COUNT_DATA,
		ROLE_ATTR_DETAIL8_UPGRADE_CARD_BUY_DATA,
		ROLE_ATTR_DETAIL8_MYTH_DATA,
		ROLE_ATTR_DETAIL8_ZODIAC_DATA,
		ROLE_ATTR_DETAIL8_CROSS_EQUIP_DATA,
		TABLE_ROLE_ATTR_DETAIL8_MAXINDEX
	};

	enum TABLE_ROLE_ATTR_DETAIL9_FIELDS
	{
		ROLE_ATTR_DETAIL9_ROLE_ATTR_DETAIL9_ID,
		ROLE_ATTR_DETAIL9_ROLE_ID,
		ROLE_ATTR_DETAIL9_RED_EQUIP_COLLECT_DATA,
		ROLE_ATTR_DETAIL9_MOUNT_DATA,
		ROLE_ATTR_DETAIL9_FOOTPRINT,
		ROLE_ATTR_DETAIL9_HALO,
		ROLE_ATTR_DETAIL9_HUGUOZHILI,
		ROLE_ATTR_DETAIL9_BAIZHAN_EQUIP_DATA,
		ROLE_ATTR_DETAIL9_FIGHT_MOUNT_DATA,
		ROLE_ATTR_DETAIL9_MOJIEFB_DATA,
		ROLE_ATTR_DETAIL9_EQUIPSUIT_DATA,
		ROLE_ATTR_DETAIL9_SHENZHUANG,
		ROLE_ATTR_DETAIL9_CSA_EQUIP_DATA,
		ROLE_ATTR_DETAIL9_SHEN_GONG,
		ROLE_ATTR_DETAIL9_SHEN_YI,
		ROLE_ATTR_DETAIL9_DISCOUNTSHOP_DATA,
		TABLE_ROLE_ATTR_DETAIL9_MAXINDEX
	};

	enum TABLE_ROLE_ID_MAP_FIELDS
	{
		ROLE_ID_MAP_IDROLE_ID_MAP,
		ROLE_ID_MAP_IS_USE,
		TABLE_ROLE_ID_MAP_MAXINDEX
	};

	enum TABLE_ROLE_NAME_MAP_FIELDS
	{
		ROLE_NAME_MAP_IDROLE_NAME_MAP,
		ROLE_NAME_MAP_DB_INDEX,
		ROLE_NAME_MAP_ROLE_ID,
		ROLE_NAME_MAP_ROLE_NAME,
		ROLE_NAME_MAP_PLAT_USER_NAME,
		TABLE_ROLE_NAME_MAP_MAXINDEX
	};

	enum TABLE_ROLESKILL_FIELDS
	{
		ROLESKILL_IDROLESKILL,
		ROLESKILL_ROLE_ID,
		ROLESKILL_SKILL_INDEX,
		ROLESKILL_FOR_INDEX,
		ROLESKILL_SKILL_LEVEL,
		ROLESKILL_SKILL_ID,
		ROLESKILL_LAST_PERFORM_TIME,
		ROLESKILL_SKILL_EXP,
		TABLE_ROLESKILL_MAXINDEX
	};

	enum TABLE_SPACERECORD_FIELDS
	{
		SPACERECORD_ID_RECORD,
		SPACERECORD_RECORD_UNQ_ID,
		SPACERECORD_OWNER_ID,
		SPACERECORD_FROM_ROLE_ID,
		SPACERECORD_TO_ROLE_ID,
		SPACERECORD_HAPPEN_TIMESTAMP,
		SPACERECORD_HAPPEN_SPACE_UID,
		SPACERECORD_TYPE,
		SPACERECORD_IS_HUIFU,
		SPACERECORD_MSG,
		TABLE_SPACERECORD_MAXINDEX
	};

	enum TABLE_SYSTEMMAIL_FIELDS
	{
		SYSTEMMAIL_SYSTEMMAIL_ID,
		SYSTEMMAIL_UID,
		SYSTEMMAIL_RECV_TIME,
		SYSTEMMAIL_KIND,
		SYSTEMMAIL_IS_READ,
		SYSTEMMAIL_IS_LOCK,
		SYSTEMMAIL_COIN,
		SYSTEMMAIL_COIN_BIND,
		SYSTEMMAIL_GOLD,
		SYSTEMMAIL_GOLD_BIND,
		SYSTEMMAIL_SUBJECT,
		SYSTEMMAIL_CONTENT,
		SYSTEMMAIL_ITEM_ID1,
		SYSTEMMAIL_ITEM_IS_BIND1,
		SYSTEMMAIL_ITEM_NUM1,
		SYSTEMMAIL_ITEM_INVALID_TIME1,
		SYSTEMMAIL_ITEM_PARAM1,
		SYSTEMMAIL_ITEM_ID2,
		SYSTEMMAIL_ITEM_IS_BIND2,
		SYSTEMMAIL_ITEM_NUM2,
		SYSTEMMAIL_ITEM_INVALID_TIME2,
		SYSTEMMAIL_ITEM_PARAM2,
		SYSTEMMAIL_ITEM_ID3,
		SYSTEMMAIL_ITEM_IS_BIND3,
		SYSTEMMAIL_ITEM_NUM3,
		SYSTEMMAIL_ITEM_INVALID_TIME3,
		SYSTEMMAIL_ITEM_PARAM3,
		SYSTEMMAIL_VIRTUAL_ITEM_DATA,
		TABLE_SYSTEMMAIL_MAXINDEX
	};

	enum TABLE_TEAMRANK_FIELDS
	{
		TEAMRANK_IDTEAMRANK,
		TEAMRANK_RANK_INDEX,
		TEAMRANK_UID1,
		TEAMRANK_UID2,
		TEAMRANK_UID3,
		TEAMRANK_USER_NAME1,
		TEAMRANK_USER_NAME2,
		TEAMRANK_USER_NAME3,
		TEAMRANK_CAMP1,
		TEAMRANK_CAMP2,
		TEAMRANK_CAMP3,
		TEAMRANK_RANK_TYPE,
		TEAMRANK_RANK_VALUE,
		TEAMRANK_FLEXIBLE_INT,
		TEAMRANK_FLEXIBLE_LL,
		TABLE_TEAMRANK_MAXINDEX
	};

	enum TABLE_TUODAN_FIELDS
	{
		TUODAN_TUODAN_ID,
		TUODAN_ROLE_ID,
		TUODAN_CREATE_TIME,
		TUODAN_NOTICE,
		TABLE_TUODAN_MAXINDEX
	};

	enum TABLE_WORLDSTATUS_FIELDS
	{
		WORLDSTATUS_IDWORLDSTATUS,
		WORLDSTATUS_FOR_INDEX,
		WORLDSTATUS_START_TIME,
		WORLDSTATUS_WORLD_TIME,
		WORLDSTATUS_LAST_UPDATE_DAYID,
		WORLDSTATUS_ACTIVITY_OPEN_RECORDS,
		WORLDSTATUS_XIANMENGZHAN_MENGZHU_ID,
		WORLDSTATUS_COMMON_DATA,
		WORLDSTATUS_CHALLENGE_FIELD_DATA,
		WORLDSTATUS_WORLD_EVENT_DATA,
		WORLDSTATUS_CSA_RANK_DATA,
		WORLDSTATUS_CSA_OTHER_DATA,
		WORLDSTATUS_REGISTER_LIMIT,
		WORLDSTATUS_BOSS_REFRESH_DATA,
		WORLDSTATUS_CROSS_GUILDBATTLE_DATA,
		WORLDSTATUS_CSA_BOSS_RANK_DATA,
		WORLDSTATUS_CROSS_RAND_ACTIVITY_DATA,
		WORLDSTATUS_CROSS_RAND_ACTIVITY_BIG_DATA,
		WORLDSTATUS_CROSS_RAND_ACTIVITY_BIG_DATA2,
		WORLDSTATUS_CROSS_RAND_ACTIVITY_CLOUD_PURCHASE_DATA,
		TABLE_WORLDSTATUS_MAXINDEX
	};

	enum TABLE_WORLDSTATUS2_FIELDS
	{
		WORLDSTATUS2_IDWORLDSTATUS2,
		WORLDSTATUS2_FOR_INDEX,
		WORLDSTATUS2_DROP_LOG_LIST_DATA,
		WORLDSTATUS2_WEDDING_DATA,
		WORLDSTATUS2_COMMON_DATA_2,
		WORLDSTATUS2_GLOBAL_PROFESS_DATA,
		WORLDSTATUS2_DROP_LOG_FB_DATA,
		WORLDSTATUS2_WORLD_ACQUISITION_LOG,
		TABLE_WORLDSTATUS2_MAXINDEX
	};

	enum TABLE_WORLDSTATUS3_FIELDS
	{
		WORLDSTATUS3_IDWORLDSTATUS3,
		WORLDSTATUS3_FOR_INDEX,
		WORLDSTATUS3_COMMON_DATA,
		WORLDSTATUS3_TOPRANK_DATA,
		WORLDSTATUS3_LOTTERY_COUNT_DATA,
		WORLDSTATUS3_RAND_ACTIVITY_DATA,
		WORLDSTATUS3_LUCKY_CLOUD_BUY_PARAM_DATA,
		TABLE_WORLDSTATUS3_MAXINDEX
	};

}

#endif

