return {
    other={
        {
            scene_id=602,
            relive_time=15,
            gather_max_times=30
        }
    },
    realive_point_list={
        {
            pos_x=101,
            pos_y=12
        }
    },
    gather={
        {
            gather_type=0,
            gather_id=184,
            gather_time=10,
            flush_time=30,
            nv_wa_shi=0,
            bind_coin=12500,
            bind_gold=0
        },
        {
            gather_type=1,
            gather_id=185,
            gather_time=15,
            flush_time=60,
            nv_wa_shi=0,
            bind_coin=25000,
            bind_gold=0
        },
        {
            gather_type=2,
            gather_id=186,
            gather_time=30,
            flush_time=120,
            nv_wa_shi=0,
            bind_coin=50000,
            bind_gold=0
        },
        {
            gather_type=3,
            gather_id=187,
            gather_time=10,
            flush_time=30,
            nv_wa_shi=1250,
            bind_coin=0,
            bind_gold=0
        },
        {
            gather_type=4,
            gather_id=188,
            gather_time=15,
            flush_time=60,
            nv_wa_shi=2500,
            bind_coin=0,
            bind_gold=0
        },
        {
            gather_type=5,
            gather_id=189,
            gather_time=30,
            flush_time=120,
            nv_wa_shi=5000,
            bind_coin=0,
            bind_gold=0
        },
        {
            gather_type=6,
            gather_id=190,
            gather_time=10,
            flush_time=30,
            nv_wa_shi=0,
            bind_coin=0,
            bind_gold=10
        },
        {
            gather_type=7,
            gather_id=191,
            gather_time=15,
            flush_time=60,
            nv_wa_shi=0,
            bind_coin=0,
            bind_gold=20
        },
        {
            gather_type=8,
            gather_id=192,
            gather_time=30,
            flush_time=120,
            nv_wa_shi=0,
            bind_coin=0,
            bind_gold=30
        },
        {
            gather_type=9,
            gather_id=193,
            gather_time=45,
            flush_time=180,
            nv_wa_shi=10000,
            bind_coin=10000,
            bind_gold=40
        }
    },
    flush_point={
        {
            gather_id=184,
            pos_x=14,
            pos_y=129
        },
        {
            gather_id=184,
            pos_x=90,
            pos_y=77
        },
        {
            gather_id=184,
            pos_x=26,
            pos_y=78
        },
        {
            gather_id=184,
            pos_x=190,
            pos_y=90
        },
        {
            gather_id=184,
            pos_x=120,
            pos_y=51
        },
        {
            gather_id=184,
            pos_x=181,
            pos_y=50
        },
        {
            gather_id=184,
            pos_x=51,
            pos_y=41
        },
        {
            gather_id=184,
            pos_x=80,
            pos_y=59
        },
        {
            gather_id=185,
            pos_x=144,
            pos_y=53
        },
        {
            gather_id=185,
            pos_x=56,
            pos_y=88
        },
        {
            gather_id=185,
            pos_x=64,
            pos_y=37
        },
        {
            gather_id=185,
            pos_x=150,
            pos_y=35
        },
        {
            gather_id=185,
            pos_x=185,
            pos_y=134
        },
        {
            gather_id=186,
            pos_x=10,
            pos_y=72
        },
        {
            gather_id=186,
            pos_x=22,
            pos_y=40
        },
        {
            gather_id=186,
            pos_x=166,
            pos_y=127
        },
        {
            gather_id=187,
            pos_x=166,
            pos_y=114
        },
        {
            gather_id=187,
            pos_x=147,
            pos_y=109
        },
        {
            gather_id=187,
            pos_x=118,
            pos_y=67
        },
        {
            gather_id=187,
            pos_x=186,
            pos_y=43
        },
        {
            gather_id=187,
            pos_x=103,
            pos_y=40
        },
        {
            gather_id=187,
            pos_x=20,
            pos_y=60
        },
        {
            gather_id=187,
            pos_x=64,
            pos_y=98
        },
        {
            gather_id=187,
            pos_x=41,
            pos_y=124
        },
        {
            gather_id=188,
            pos_x=162,
            pos_y=139
        },
        {
            gather_id=188,
            pos_x=190,
            pos_y=74
        },
        {
            gather_id=188,
            pos_x=149,
            pos_y=21
        },
        {
            gather_id=188,
            pos_x=65,
            pos_y=75
        },
        {
            gather_id=188,
            pos_x=18,
            pos_y=117
        },
        {
            gather_id=189,
            pos_x=44,
            pos_y=99
        },
        {
            gather_id=189,
            pos_x=164,
            pos_y=81
        },
        {
            gather_id=189,
            pos_x=131,
            pos_y=140
        },
        {
            gather_id=190,
            pos_x=37,
            pos_y=77
        },
        {
            gather_id=190,
            pos_x=73,
            pos_y=59
        },
        {
            gather_id=190,
            pos_x=45,
            pos_y=18
        },
        {
            gather_id=190,
            pos_x=135,
            pos_y=48
        },
        {
            gather_id=190,
            pos_x=156,
            pos_y=42
        },
        {
            gather_id=190,
            pos_x=181,
            pos_y=69
        },
        {
            gather_id=190,
            pos_x=150,
            pos_y=101
        },
        {
            gather_id=190,
            pos_x=186,
            pos_y=125
        },
        {
            gather_id=191,
            pos_x=150,
            pos_y=123
        },
        {
            gather_id=191,
            pos_x=144,
            pos_y=71
        },
        {
            gather_id=191,
            pos_x=81,
            pos_y=39
        },
        {
            gather_id=191,
            pos_x=35,
            pos_y=45
        },
        {
            gather_id=191,
            pos_x=31,
            pos_y=131
        },
        {
            gather_id=192,
            pos_x=178,
            pos_y=30
        },
        {
            gather_id=192,
            pos_x=103,
            pos_y=53
        },
        {
            gather_id=192,
            pos_x=157,
            pos_y=62
        },
        {
            gather_id=193,
            pos_x=12,
            pos_y=104
        },
        {
            gather_id=193,
            pos_x=184,
            pos_y=105
        }
    }
}