return {
    levelcfg={
        {
            level=0,
            layer=0,
            scene_id=1700,
            boss_id=30800,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=1,
            scene_id=1701,
            boss_id=30801,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=2,
            scene_id=1702,
            boss_id=30802,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=3,
            scene_id=1703,
            boss_id=30803,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=4,
            scene_id=1704,
            boss_id=30804,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=5,
            scene_id=1705,
            boss_id=30805,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=6,
            scene_id=1706,
            boss_id=30806,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=7,
            scene_id=1707,
            boss_id=30807,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=8,
            scene_id=1708,
            boss_id=30808,
            boss_x=42,
            boss_y=58
        },
        {
            level=0,
            layer=9,
            scene_id=1709,
            boss_id=30809,
            boss_x=42,
            boss_y=58
        },
        {
            level=1,
            layer=0,
            scene_id=1111,
            boss_id=30810,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=1,
            scene_id=1112,
            boss_id=30811,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=2,
            scene_id=1113,
            boss_id=30812,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=3,
            scene_id=1114,
            boss_id=30813,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=4,
            scene_id=1115,
            boss_id=30814,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=5,
            scene_id=1116,
            boss_id=30815,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=6,
            scene_id=1117,
            boss_id=30816,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=7,
            scene_id=1118,
            boss_id=30817,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=8,
            scene_id=1119,
            boss_id=30818,
            boss_x=47,
            boss_y=43
        },
        {
            level=1,
            layer=9,
            scene_id=1120,
            boss_id=30819,
            boss_x=47,
            boss_y=43
        },
        {
            level=2,
            layer=0,
            scene_id=1121,
            boss_id=30820,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=1,
            scene_id=1122,
            boss_id=30821,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=2,
            scene_id=1123,
            boss_id=30822,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=3,
            scene_id=1124,
            boss_id=30823,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=4,
            scene_id=1125,
            boss_id=30824,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=5,
            scene_id=1126,
            boss_id=30825,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=6,
            scene_id=1127,
            boss_id=30826,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=7,
            scene_id=1128,
            boss_id=30827,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=8,
            scene_id=1129,
            boss_id=30828,
            boss_x=51,
            boss_y=41
        },
        {
            level=2,
            layer=9,
            scene_id=1130,
            boss_id=30829,
            boss_x=51,
            boss_y=41
        },
        {
            level=3,
            layer=0,
            scene_id=1131,
            boss_id=30830,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=1,
            scene_id=1132,
            boss_id=30831,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=2,
            scene_id=1133,
            boss_id=30832,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=3,
            scene_id=1134,
            boss_id=30833,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=4,
            scene_id=1135,
            boss_id=30834,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=5,
            scene_id=1136,
            boss_id=30835,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=6,
            scene_id=1137,
            boss_id=30836,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=7,
            scene_id=1138,
            boss_id=30837,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=8,
            scene_id=1139,
            boss_id=30838,
            boss_x=61,
            boss_y=39
        },
        {
            level=3,
            layer=9,
            scene_id=1140,
            boss_id=30839,
            boss_x=61,
            boss_y=39
        },
        {
            level=4,
            layer=0,
            scene_id=1141,
            boss_id=30840,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=1,
            scene_id=1142,
            boss_id=30841,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=2,
            scene_id=1143,
            boss_id=30842,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=3,
            scene_id=1144,
            boss_id=30843,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=4,
            scene_id=1145,
            boss_id=30844,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=5,
            scene_id=1146,
            boss_id=30845,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=6,
            scene_id=1147,
            boss_id=30846,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=7,
            scene_id=1148,
            boss_id=30847,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=8,
            scene_id=1149,
            boss_id=30848,
            boss_x=42,
            boss_y=33
        },
        {
            level=4,
            layer=9,
            scene_id=1150,
            boss_id=30849,
            boss_x=42,
            boss_y=33
        },
        {
            level=5,
            layer=0,
            scene_id=1151,
            boss_id=30850,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=1,
            scene_id=1152,
            boss_id=30851,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=2,
            scene_id=1153,
            boss_id=30852,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=3,
            scene_id=1154,
            boss_id=30853,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=4,
            scene_id=1155,
            boss_id=30854,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=5,
            scene_id=1156,
            boss_id=30855,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=6,
            scene_id=1157,
            boss_id=30856,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=7,
            scene_id=1158,
            boss_id=30857,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=8,
            scene_id=1159,
            boss_id=30858,
            boss_x=57,
            boss_y=35
        },
        {
            level=5,
            layer=9,
            scene_id=1160,
            boss_id=30859,
            boss_x=57,
            boss_y=35
        }
    },
    chaptercfg={
        {
            level=0,
            pos_x=44,
            pos_y=24,
            role_level=30,
            three_star_min_time=0,
            three_star_max_time=60,
            three_star_reward_item={
                item_id=26000,
                num=13,
                is_bind=1
            },
            two_star_min_time=61,
            two_star_max_time=120,
            two_star_reward_item={
                item_id=26000,
                num=7,
                is_bind=1
            },
            one_star_min_time=121,
            one_star_max_time=86400,
            one_star_reward_item={
                item_id=26000,
                num=1,
                is_bind=1
            }
        },
        {
            level=1,
            pos_x=13,
            pos_y=7,
            role_level=30,
            three_star_min_time=0,
            three_star_max_time=60,
            three_star_reward_item={
                item_id=26000,
                num=14,
                is_bind=1
            },
            two_star_min_time=61,
            two_star_max_time=120,
            two_star_reward_item={
                item_id=26000,
                num=8,
                is_bind=1
            },
            one_star_min_time=121,
            one_star_max_time=86400,
            one_star_reward_item={
                item_id=26000,
                num=2,
                is_bind=1
            }
        },
        {
            level=2,
            pos_x=17,
            pos_y=20,
            role_level=30,
            three_star_min_time=0,
            three_star_max_time=60,
            three_star_reward_item={
                item_id=26000,
                num=15,
                is_bind=1
            },
            two_star_min_time=61,
            two_star_max_time=120,
            two_star_reward_item={
                item_id=26000,
                num=9,
                is_bind=1
            },
            one_star_min_time=121,
            one_star_max_time=86400,
            one_star_reward_item={
                item_id=26000,
                num=3,
                is_bind=1
            }
        },
        {
            level=3,
            pos_x=18,
            pos_y=29,
            role_level=30,
            three_star_min_time=0,
            three_star_max_time=60,
            three_star_reward_item={
                item_id=26000,
                num=16,
                is_bind=1
            },
            two_star_min_time=61,
            two_star_max_time=120,
            two_star_reward_item={
                item_id=26000,
                num=10,
                is_bind=1
            },
            one_star_min_time=121,
            one_star_max_time=86400,
            one_star_reward_item={
                item_id=26000,
                num=4,
                is_bind=1
            }
        },
        {
            level=4,
            pos_x=29,
            pos_y=9,
            role_level=30,
            three_star_min_time=0,
            three_star_max_time=60,
            three_star_reward_item={
                item_id=26000,
                num=17,
                is_bind=1
            },
            two_star_min_time=61,
            two_star_max_time=120,
            two_star_reward_item={
                item_id=26000,
                num=11,
                is_bind=1
            },
            one_star_min_time=121,
            one_star_max_time=86400,
            one_star_reward_item={
                item_id=26000,
                num=5,
                is_bind=1
            }
        },
        {
            level=5,
            pos_x=20,
            pos_y=12,
            role_level=30,
            three_star_min_time=0,
            three_star_max_time=60,
            three_star_reward_item={
                item_id=26000,
                num=18,
                is_bind=1
            },
            two_star_min_time=61,
            two_star_max_time=120,
            two_star_reward_item={
                item_id=26000,
                num=12,
                is_bind=1
            },
            one_star_min_time=121,
            one_star_max_time=86400,
            one_star_reward_item={
                item_id=26000,
                num=6,
                is_bind=1
            }
        }
    },
    other={
        {
            auto_item_id=26916,
            auto_item_num=1,
            reset_cost=50
        }
    },
    buy_cost={
        {
            buy_times=1,
            gold_cost=50
        },
        {
            buy_times=2,
            gold_cost=50
        },
        {
            buy_times=3,
            gold_cost=50
        },
        {
            buy_times=4,
            gold_cost=50
        },
        {
            buy_times=5,
            gold_cost=50
        }
    }
}