return {
    chongzhi_rank={
        {
            opengame_day=7,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=7,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=7,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=7,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=7,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=7,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=7,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=14,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=14,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=14,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=14,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=14,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=14,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=14,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=21,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=21,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=21,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=21,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=21,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=21,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=21,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=28,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=28,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=28,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=28,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=28,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=28,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=28,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=35,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=35,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=35,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=35,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=35,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=35,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=35,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=42,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=42,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=42,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=42,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=42,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=42,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=42,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=49,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=49,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=49,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=49,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=49,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=49,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=49,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=999999,
            rank_index=0,
            reward_item={
                item_id=30519,
                num=1,
                is_bind=1
            },
            limit_chongzhi=6888
        },
        {
            opengame_day=999999,
            rank_index=1,
            reward_item={
                item_id=30520,
                num=1,
                is_bind=1
            },
            limit_chongzhi=5888
        },
        {
            opengame_day=999999,
            rank_index=2,
            reward_item={
                item_id=30521,
                num=1,
                is_bind=1
            },
            limit_chongzhi=3888
        },
        {
            opengame_day=999999,
            rank_index=3,
            reward_item={
                item_id=30522,
                num=1,
                is_bind=1
            },
            limit_chongzhi=1888
        },
        {
            opengame_day=999999,
            rank_index=4,
            reward_item={
                item_id=30523,
                num=1,
                is_bind=1
            },
            limit_chongzhi=888
        },
        {
            opengame_day=999999,
            rank_index=5,
            reward_item={
                item_id=30524,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        },
        {
            opengame_day=999999,
            rank_index="6-9",
            reward_item={
                item_id=30525,
                num=1,
                is_bind=1
            },
            limit_chongzhi=88
        }
    },
    rand_total_chongzhi={
        {
            opengame_day=7,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=7,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=14,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=21,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=28,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=35,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=42,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=49,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=0,
            need_chongzhi=500,
            reward_item={
                [0]={
                    item_id=30390,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=1,
            need_chongzhi=1000,
            reward_item={
                [0]={
                    item_id=30391,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=2,
            need_chongzhi=2000,
            reward_item={
                [0]={
                    item_id=30392,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=3,
            need_chongzhi=3000,
            reward_item={
                [0]={
                    item_id=30393,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=4,
            need_chongzhi=6000,
            reward_item={
                [0]={
                    item_id=30394,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=5,
            need_chongzhi=12000,
            reward_item={
                [0]={
                    item_id=30395,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=6,
            need_chongzhi=25000,
            reward_item={
                [0]={
                    item_id=30396,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=7,
            need_chongzhi=50000,
            reward_item={
                [0]={
                    item_id=30397,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=8,
            need_chongzhi=100000,
            reward_item={
                [0]={
                    item_id=30398,
                    num=1,
                    is_bind=1
                }
            }
        },
        {
            opengame_day=999999,
            seq=9,
            need_chongzhi=200000,
            reward_item={
                [0]={
                    item_id=30399,
                    num=1,
                    is_bind=1
                }
            }
        }
    }
}