return {
	"core/bindtool",
	"core/baseclass",
	"core/basehotupdate",
	"core/baseprotocolstruct",
	"core/debug_tool",
	"core/util",
	"core/checkpolicy",
	"core/ctoluafun",
	"core/ctoluafun_auto",
	"core/cfactory",
	"core/enumadapter",
	"core/strong",

	"hotupdate",

	"data/rolecommondata",
	"data/worldcommondata",
	"data/gameenum",
	"data/language",
	"data/constant",

	"db/dbdefine",
	"db/basedb",
	"db/roledb",
	"db/worlddb",

	"protocol/protocol_adapter",
	"protocol/protocol_150",
	"protocol/protocol_151",

	"manager/dbmanager",
	"manager/gmmanager",
	"manager/logicconfigmanager",
	"manager/rolemanager",
	"manager/messagehandlermanager",
	"manager/scenemanager",
	"manager/monstermanager",
	"manager/speciallogicmanager",
	"manager/fbmanager",
	"manager/worldmanager",
	"manager/itemmanager",
	"manager/vipmanager",
	"manager/memmanager",
	"manager/activitymanager",
	"manager/joinlimitmanager",
	"manager/eventmanager",

  	"module/activity/baseactivity",
  	"module/activity/shuijingact",
  	"module/activity/shuijingactconfig",

    "module/fb/tianxiangefb",
    "module/fb/tianxiangefbconfig",
    "module/fb/challengefb",
    "module/fb/challengefbconfig",

    "module/speciallogic/speciallogic",
	"module/speciallogic/specialtianxiange",
	"module/speciallogic/specialchallenge",
	"module/speciallogic/specialshuijing",

	"module/obj/role",
    "module/lingyu/lingyu",
    "module/lingyu/lingyuconfig",
}