#ifndef __CHENG_ZHANG_DAN_CONFIG_H__
#define __CHENG_ZHANG_DAN_CONFIG_H__

enum CHENGZHANGDAN_TYPE
{
	CHENGZHANGDAN_TYPE_INVALID = 0,
	CHENGZHANGDAN_TYPE_MOUNT,
	CHENGZHANGDAN_TYPE_WING,
	CHENGZHANGDAN_TYPE_HALO,
	CHENGZHANGDAN_TYPE_SHENGONG,
	CHENGZHANGDAN_TYPE_SHENYI,

	CHENGZHANGDAN_TYPE_MAX,
};

#endif