#ifndef __ROLE_GOAL_DEF_HPP__
#define __ROLE_GOAL_DEF_HPP__

#include "servercommon/servercommon.h"

enum ROLE_GOAL_COND_TYPE
{
	ROLE_GOAL_COND_TYPE_INVALID = 0,
	ROLE_GOAL_TYPE_EXP_FB_STAR,
	ROLE_GOAL_TYPE_EQUIP_FB_STAR,
	ROLE_GOAL_TYPE_PASS_TOWERDEFEND_FB,
	ROLE_GOAL_TYPE_ENTER_CHALLENGE_FB,
	ROLE_GOAL_TYPE_ZHANSHENDIAN_LEVEL,
	ROLE_GOAL_TYPE_EQUIP_STRENGTHEN_TOTAL_LEVEL,
	ROLE_GOAL_TYPE_MOUNT_GRADE,
	ROLE_GOAL_TYPE_WING_JINGHUA,
	ROLE_GOAL_TYPE_GENGU_TOTAL_JINGJIE,
	ROLE_GOAL_TYPE_MARRY,
	ROLE_GOAL_TYPE_ACTIVE_JIANHUN_SKILL_COUNT,
	ROLE_GOAL_TYPE_STONE_TOTAL_LEVEL,
	ROLE_GOAL_TYPE_ACTIVE_XIANNV_COUNT,
	ROLE_GOAL_TYPE_XIANNV_CHANMIAN_LEVEL,
	ROLE_GOAL_TYPE_SHEN_EQUIP_COUNT,

	ROLE_GOAL_COND_TYPE_MAX,
};

enum ROLE_GOAL_COMPARE_TYPE
{
	ROLE_GOAL_COMPARE_TYPE_NOT_COMPARE = 0,
	ROLE_GOAL_COMPARE_TYPE_NOT_LESS,

	ROLE_GOAL_COMPARE_TYPE_MAX,
};

#endif

