#ifndef __TRIGGER_DEF_H__
#define __TRIGGER_DEF_H__

#include "servercommon/servercommon.h"

static const int TRIGGER_COND_PARAM_MAX = 2;						// 触发条件参数个数
static const int TRIGGER_ACTION_PARAM_MAX = 4;						// 触发动作参数个数

enum TRIGGER_COND_TYPE
{
	TRIGGER_COND_TYPE_INVALID = 0,

	TRIGGER_COND_TYPE_ENTER_SCENE,									// 进入场景
	TRIGGER_COND_TYPE_ENTER_AREA,									// 进入区域
	TRIGGER_COND_TYPE_FB_PASS,										// 副本通关
	TRIGGER_COND_TYPE_MONSTER_DIE,									// 指定怪物死亡

	TRIGGER_COND_TYPE_MAX
};

enum TRIGGER_ACTION_TYPE
{
	TRIGGER_ACTION_TYPE_INVALID = 0,

	TRIGGER_ACTION_TYPE_CREATE_MONSTER,								// 刷怪
	TRIGGER_ACTION_TYPE_SURROUND_MONSTER,							// 出埋伏怪
	TRIGGER_ACTION_TYPE_SET_FB_FOLLOW_NPC,							// 设置副本跟随NPC
	TRIGGER_ACTION_TYPE_RESET_FB_FOLLOW_NPC,						// 取消副本跟随NPC
	TRIGGER_ACTION_TYPE_SPECIAL_DICI,								// 地刺
	TRIGGER_ACTION_TYPE_SPECIAL_BEILAO,								// 焙烙
	TRIGGER_ACTION_TYPE_SPECIAL_BANMASUO,							// 绊马索
	TRIGGER_ACTION_TYPE_PLAY_STORY,									// 播放剧情
	TRIGGER_ACTION_TYPE_CREATE_MONSTER_APPOINT_POS,					// 定点刷怪
	TRIGGER_ACTION_TYPE_SPECIALLOGIC,								// 触发场景特殊逻辑
	TRIGGER_ACTION_TYPE_ICE_LANDMINE,								// 冰霜地雷
	TRIGGER_ACTION_TYPE_FIRE_LANDMINE,								// 火焰地雷

	TRIGGER_ACTION_TYPE_MAX
};

enum TRIGGER_SPECIALLOGIC_PARAM0									// 触发场景特殊逻辑 trigger_action_param_list[0]
{
	TRIGGER_SPECIALLOGIC_PARAM0_YJQMS_SKILL = 0,					// 御剑秋名山 技能
	TRIGGER_SPECIALLOGIC_PARAM0_YJQMS_XIANGJIAOPI,					// 御剑秋名山 香蕉皮
};

#endif	// __TRIGGER_DEF_H__

